import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LayoutWithConditionalRendering from "@/components/LayoutWithConditionalRendering";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Citiguard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-background text-foreground`}>
        <LayoutWithConditionalRendering>
          {children}
        </LayoutWithConditionalRendering>
      </body>
    </html>
  );
}
